spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://192.168.4.37:3306/iob?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sisa
    password: ENC(NoLInuIXCZTlwYPVtu+2vA==)
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate: 
      ddl-auto: none
    show-sql: true
    properties: 
      hibernate:  
        format_sql: true
        highlight_sql: true
  flyway:
    baseline-on-migrate: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true # 쿼리를 줄바꿈해서 예쁘게 보여줌
      logging: slf4j
      tracing:
        include-parameter-values: true # 파라미터 값 포함 여부
logging:
  level:
    root: info                          # 전체 기본값은 info
    com.project.domain.auth: debug       # 내 소스 코드는 상세히(debug)
    org.hibernate.SQL: info
    org.apache.coyote: info
    org.apache.tomcat: info
file:
  upload-path: ${FILE_UPLOAD_PATH:C:/temp/uploads/} # 환경 변수가 없으면 C드라이브 사용
  resource-path: /images/**
swagger:
  server-url: http://localhost:8080