spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    group:
      local: "local,common"
      dev: "dev,common"
      prod: "prod,common"

# --- 여기서부터는 모든 환경 공통 설정 ---
  application:
    name: sisa-project

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false
    time-zone: Asia/Seoul

springdoc:
  swagger-ui:
    persist-authorization: true
    doc-expansion: list

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:  
  secret: ${JWT_SECRET:ENC(53hWAIu/kM3EwR7Rcbk3d0S0yiuc5NV6bHpzeZkKr3MYjUNT10RxbDt44sHjn4DVEurNUa8AH65xtxw9Q5TPPZr94Q1Kl+SChj3U2fADo3s=)}
  access-token-expiration: 1800000 
  refresh-token-expiration: 604800000 

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

jasypt:
  encryptor:
  # OS 환경변수에 'JASYPT_PASSWORD'라는 이름으로 저장된 값을 가져와서 마스터키로 써라!
    password: ${JASYPT_PASSWORD}